/**
 * Movies Actions
 */

export const MOVIES_REQUEST_PENDING = 'MOVIES_REQUEST_PENDING'
export const MOVIES_REQUEST_SUCCESS = 'MOVIES_REQUEST_SUCCESS'
export const MOVIES_REQUEST_ERROR = 'MOVIES_REQUEST_ERROR'
export const MOVIES_SORT = 'MOVIES_SORT'


/**
 * Movie details actions
 */
export const MOVIE_RANKING_REQUEST_PENDING = 'MOVIE_RANKING_REQUEST_PENDING'
export const MOVIE_RANKING_REQUEST_SUCCESS = 'MOVIE_RANKING_REQUEST_SUCCESS'
export const MOVIE_RANKING_REQUEST_ERROR = 'MOVIE_RANKING_REQUEST_ERROR'
