/**
 * Movies Actions
 */

export const MOVIES_REQUEST_PENDING = 'MOVIES_REQUEST_PENDING'
export const MOVIES_REQUEST_SUCCESS = 'MOVIES_REQUEST_SUCCESS'
export const MOVIES_REQUEST_ERROR = 'MOVIES_REQUEST_ERROR'
